#pragma once

#include <stddef.h>
#include <stdint.h>
#include <Kernel/Interface/System.hpp>
#include <Kernel/Interface/Types.hpp>
#include <sys/stat.h>
#include <sys/types.h>

ssize_t sys$write(int fd, const void *buffer, size_t count);
ssize_t sys$read(int fd, void *buffer, size_t count);
int sys$open(const char *pathname, int flags, int mode);
int sys$close(int fd);
int sys$fstat(int fd, struct stat *statbuf);
int sys$wait(int *wstatus);
int sys$chdir(const char *pathname);
int sys$posix_spawn(
    pid_t *pid,
    const char *pathname,
    const posix_spawn_file_actions_t *file_actions,
    const posix_spawnattr_t *attrp,
    char **argv,
    char **envp);
int sys$get_working_directory(void *buffer, size_t *buffer_size);

_Noreturn
void sys$exit(int status);

// Returns base address where the readonly data section is loaded
uint32_t sys$get_readonly_base();

// Returns base address where the writeable data section is loaded
uint32_t sys$get_writable_base();

// Symbol generated by linker at beginning of writable data section
extern void __libc_static_base;

// The 'R_ARM_SBREL32' relocation does not appear to be supported by the linker
// Therefore, we need to compute the relocation manually
#define access_mutable_global(variable_name, variable_type) \
    (*(variable_type*)(sys$get_writable_base() + ((void*)&variable_name - (void*)&__libc_static_base)))

// The 'R_ARM_SBREL32' relocation does not appear to be supported by the linker
// Therefore, we need to compute the relocation manually
#define access_mutable_global_array(variable_name, variable_type) \
    (*(variable_type(*)[])(sys$get_writable_base() + ((void*)&variable_name - (void*)&__libc_static_base)))
